// Generated by svg2orca.py from lapel_pin.svg.
// Rebuild the Orca 3MF after editing: python3 svg2orca.py lapel_pin.scad

svg = "lapel_pin.svg";

// [SVG layer id, height (mm), color, outline width (mm, 0 = filled as drawn)]
// Bottom to top: each layer covers the ones before it.
layers = [
    ["Layer_5",   3, "#FFFFFF", 0],
    ["Cloud",     4, "#000000", 0.4],
    ["Outer",     4, "#00FF00", 0.4],
    ["Middle",    4, "#0000FF", 0.4],
    ["Inner",     4, "#FF00FF", 0.4],
    ["Lightning", 5, "#FFFF00", 0.4],
    ["Stars",     5, "#FFFF00", 0]
];

// Tiny offset that re-cleans the imported polygons (self-intersecting paths).
clean = 0.001;

// Line of the given width centered on the shape's edge.
module outline(width) {
    difference() {
        offset(r = width / 2) children();
        offset(r = -width / 2) children();
    }
}

module footprint(l) {
    if (l[3] > 0) outline(l[3]) offset(delta = clean) import(svg, id = l[0]);
    else offset(delta = clean) import(svg, id = l[0]);
}

// Footprint of layer i with every later layer cut out, so no two layers
// overlap and each region belongs to exactly one filament in the slicer.
module exclusive_footprint(i) {
    difference() {
        footprint(layers[i]);
        if (i < len(layers) - 1)
            for (j = [i + 1 : len(layers) - 1]) footprint(layers[j]);
    }
}

for (i = [0 : len(layers) - 1])
    color(layers[i][2])
        linear_extrude(height = layers[i][1])
            exclusive_footprint(i);
